# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'IngKe' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IngKe
pod 'SDWebImage', '~> 3.8.1'
pod 'AFNetworking', '~> 3.1.0'
pod 'LFLiveKit'
pod 'YYKit'
pod 'MJExtension', '~> 3.0.13'
pod 'SVProgressHUD', '~> 2.1'
pod 'Masonry', '~> 1.0.2'


end
